### ISSUE TITLE
Upama displays only white page after "generate apparatus"

### ISSUE THREAD

**Issue by ppasedach** [chchch/upama#60]
`[Wed Jul 19 05:47:19.702452 2023] [php7:error] [pid 18245] [client 85.183.14.116:60048] PHP Fatal error:  Uncaught Error: Call to a member function query() on string in /var/www/muk.li/upama/lib/plugins/upama/upama.php:1316\nStack trace:\n#0 /var/www/muk.li/upama/lib/plugins/upama/upama.php(1238): Upama->getWitGroups(Array)\n#1 /var/www/muk.li/upama/lib/plugins/upama/syntax.php(287): Upama->collate(Array)\n#2 /var/www/muk.li/upama/inc/parser/handler.php(279): syntax_plugin_upama->handle('<TEI xmlns="htt...', 5, 1, Object(Doku_Handler))\n#3 /var/www/muk.li/upama/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('<TEI xmlns="htt...', 5, 1, 'upama')\n#4 /var/www/muk.li/upama/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\\Parsing\\Lexer\\Lexer->invokeHandler('<TEI xmlns="htt...', 5, 1)\n#5 /var/www/muk.li/upama/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\\Parsing\\Lexer\\Lexer->dispatchTokens('', '<TEI xmlns="htt...', '_plugin_upama', 1, 1)\n#6 /var/www/muk.li/upama/inc/Parsing/Parser.php(109): dokuwiki\\Parsing\\Lexer\\Lexer->parse('\\n\\n')\n#7 /var/www/muk.li/upama/inc/parserutils.php(216): dokuwiki\\Parsing\\Parser->parse('\\n<TEI xml in /var/www/muk.li/upama/lib/plugins/upama/upama.php on line 1316, referer: https://muk.li/upama/haravijaya:03:hv-03-p
`

**Comment by ppasedach** [comment]
One reason I could imagine this to happen could maybe be that there's an unusual collation element, a `<p>` inside a `<note>`.

**Comment by ppasedach** [comment]
I confirm that if I exclude the `<p>` inside the `<note>` from the collation, the collation works again.

**Comment by chchch** [comment]
Weird, TEI actually allows `<p>` inside `<note>`...
